name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Run Selenium tests
      run: |
        python -c "
        from utilities.helper import Helper
        from pages.login_page import LoginPage
        from pages.products_page import ProductsPage
        
        print('🧪 Starting comprehensive CI/CD test...')
        
        # Test 1: Login functionality
        driver = Helper.setup_driver(headless=True)
        login_page = LoginPage(driver)
        login_page.navigate_to_login().login('standard_user', 'secret_sauce')
        print('✅ Login test passed!')
        
        # Test 2: Products functionality
        products_page = ProductsPage(driver)
        products_page.add_backpack_to_cart()
        print('✅ Products test passed!')
        
        # Test 3: Screenshot capability
        Helper.take_screenshot(driver, 'ci_cd_comprehensive')
        print('✅ Screenshot test passed!')
        
        driver.quit()
        print('🎉 All CI/CD tests passed!')
        "