name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Run basic login test
      run: |
        python -c "
        from utilities.helper import Helper
        from pages.login_page import LoginPage
        print('🧪 Testing login functionality...')
        driver = Helper.setup_driver(headless=True)
        login_page = LoginPage(driver)
        login_page.navigate_to_login().login('standard_user', 'secret_sauce')
        print('✅ Login test passed!')
        driver.quit()
        "

    - name: Run products test
      run: |
        python -c "
        from utilities.helper import Helper
        from pages.login_page import LoginPage
        from pages.products_page import ProductsPage
        print('🧪 Testing products functionality...')
        driver = Helper.setup_driver(headless=True)
        login_page = LoginPage(driver)
        products_page = ProductsPage(driver)
        login_page.navigate_to_login().login('standard_user', 'secret_sauce')
        products_page.add_backpack_to_cart()
        print('✅ Products test passed!')
        driver.quit()
        "