name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox with GeckoDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        
        # Install specific Firefox version that works with Selenium
        wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        sudo tar -xjf firefox.tar.bz2 -C /opt/
        sudo ln -sf /opt/firefox/firefox /usr/local/bin/firefox

    - name: Run Selenium tests
      run: |
        python -c "
        from utilities.helper import Helper
        from pages.login_page import LoginPage
        print('🧪 Starting CI/CD test with environment detection...')
        driver = Helper.setup_driver(headless=True)
        login_page = LoginPage(driver)
        login_page.navigate_to_login().login('standard_user', 'secret_sauce')
        print('✅ Login test passed!')
        driver.quit()
        "
