name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox (simple approach)
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Run simple Selenium test
      run: |
        python -c "
        import os
        print('🏗️ CI/CD Environment:', os.getenv('GITHUB_ACTIONS'))
        
        # Test basic imports first
        from utilities.helper import Helper
        from pages.login_page import LoginPage
        
        print('🧪 Starting simple CI/CD test...')
        
        # Use headless mode for CI/CD
        driver = Helper.setup_driver(headless=True)
        print('✅ Browser setup successful!')
        
        # Simple test - just navigate and check title
        driver.get('https://www.saucedemo.com')
        print('✅ Page loaded. Title:', driver.title)
        
        # Basic login test
        login_page = LoginPage(driver)
        login_page.login('standard_user', 'secret_sauce')
        print('✅ Login completed!')
        
        driver.quit()
        print('🎉 CI/CD test passed!')
        "